insert into car_table (car_model, car_release_year, car_color, car_company) values ('DBS', 2012, 'Maroon', 'Aston Martin');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Prius', 2011, 'Red', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Corolla', 2001, 'Yellow', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Suburban 2500', 1996, 'Green', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Spectra', 2002, 'Maroon', 'Kia');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Thunderbird', 1967, 'Pink', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Sidekick', 1990, 'Green', 'Suzuki');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('X5', 2004, 'Goldenrod', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Traverse', 2012, 'Mauv', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Corolla', 2011, 'Yellow', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Silverado 3500', 2007, 'Turquoise', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Villager', 2001, 'Aquamarine', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Malibu', 2006, 'Maroon', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('RSX', 2006, 'Teal', 'Acura');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Tiburon', 2008, 'Maroon', 'Hyundai');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('5 Series', 1994, 'Pink', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Grand Voyager', 2000, 'Orange', 'Plymouth');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Prius', 2008, 'Maroon', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('300SL', 1993, 'Maroon', 'Mercedes-Benz');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('S-Class', 2007, 'Teal', 'Mercedes-Benz');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Altima', 2012, 'Maroon', 'Nissan');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Somerset', 1986, 'Fuscia', 'Buick');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental', 1990, 'Blue', 'Lincoln');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Galant', 1985, 'Orange', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental GTC', 2007, 'Blue', 'Bentley');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Topaz', 1984, 'Red', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental', 1990, 'Fuscia', 'Lincoln');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cougar', 2001, 'Turquoise', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Topaz', 1993, 'Violet', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('A8', 2012, 'Maroon', 'Audi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Civic', 1985, 'Green', 'Honda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('MKX', 2010, 'Puce', 'Lincoln');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Panamera', 2011, 'Fuscia', 'Porsche');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Silhouette', 2002, 'Yellow', 'Oldsmobile');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Explorer Sport Trac', 2000, 'Green', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Sidekick', 1993, 'Green', 'Suzuki');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('430', 1990, 'Teal', 'Maserati');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cherokee', 2000, 'Purple', 'Jeep');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('CR-V', 1997, 'Mauv', 'Honda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('E350', 2010, 'Puce', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('6000', 1990, 'Mauv', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('LTD', 1984, 'Purple', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rodeo', 2004, 'Orange', 'Isuzu');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Mariner', 2008, 'Maroon', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Bonneville', 1968, 'Orange', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Golf', 1996, 'Aquamarine', 'Volkswagen');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('RVR', 1995, 'Teal', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Celica', 2004, 'Fuscia', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Monterey', 2004, 'Blue', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Outlander', 2012, 'Goldenrod', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('5 Series', 1992, 'Teal', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Achieva', 1995, 'Fuscia', 'Oldsmobile');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('3000GT', 1995, 'Turquoise', 'Mitsubishi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('940', 1994, 'Teal', 'Volvo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('GTO', 2006, 'Purple', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('F-Series Super Duty', 2007, 'Green', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Savana 3500', 2002, 'Fuscia', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('B-Series', 2007, 'Orange', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('626', 1997, 'Puce', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Land Cruiser', 1998, 'Blue', 'Toyota');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rendezvous', 2003, 'Mauv', 'Buick');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('300M', 2003, 'Khaki', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Bonneville', 1995, 'Teal', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('C70', 2013, 'Puce', 'Volvo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Prizm', 1993, 'Khaki', 'Geo');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Thunderbird', 1972, 'Indigo', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('LeSabre', 1997, 'Purple', 'Buick');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('F350', 2003, 'Maroon', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Jetta', 2000, 'Khaki', 'Volkswagen');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('C8 Double 12 S', 2006, 'Green', 'Spyker');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Neon', 2000, 'Green', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('S4', 2002, 'Maroon', 'Audi');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Yukon', 2005, 'Khaki', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('DB9', 2007, 'Maroon', 'Aston Martin');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Dakota Club', 2001, 'Crimson', 'Dodge');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('M6', 2009, 'Mauv', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('C-MAX Hybrid', 2013, 'Teal', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('B-Series', 1993, 'Violet', 'Mazda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('350Z', 2007, 'Pink', 'Nissan');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Yukon', 2007, 'Teal', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('645', 2004, 'Yellow', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('900', 1993, 'Khaki', 'Saab');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Accord', 2009, 'Aquamarine', 'Honda');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Marquis', 1984, 'Turquoise', 'Mercury');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('M3', 1997, 'Puce', 'BMW');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('3500 Club Coupe', 1996, 'Red', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Envoy', 2000, 'Goldenrod', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Canyon', 2010, 'Khaki', 'GMC');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Escalade EXT', 2007, 'Red', 'Cadillac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Continental', 2008, 'Purple', 'Bentley');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('LS Hybrid', 2011, 'Crimson', 'Lexus');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Cayenne', 2004, 'Orange', 'Porsche');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('PT Cruiser', 2006, 'Crimson', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Tahoe', 2003, 'Red', 'Chevrolet');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('G5', 2008, 'Mauv', 'Pontiac');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Rio', 2006, 'Crimson', 'Kia');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Town & Country', 1998, 'Crimson', 'Chrysler');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('F-Series', 2001, 'Teal', 'Ford');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('CL', 2003, 'Green', 'Acura');
insert into car_table (car_model, car_release_year, car_color, car_company) values ('Swift', 1987, 'Puce', 'Suzuki');